# Generated by Django 5.0.6 on 2024-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_magazineproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazineproduct',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
