# Generated by Django 5.0.6 on 2024-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_alter_magazine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='stock_level',
            field=models.IntegerField(default=1),
        ),
    ]
