# Generated by Django 5.0.6 on 2024-06-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_alter_catalog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='stock_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='catalogproducts',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
