# Generated by Django 5.0.6 on 2024-06-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_alter_catalogproduct_stock_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogproduct',
            name='stock_level',
        ),
        migrations.AddField(
            model_name='catalogproducts',
            name='stock_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
